# 线上配置文件
# @author 小鹿
# @from /
server:
  port: 8101
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/my_db
    username: root
    password: xxx
# rabbitmq 配置
  rabbitmq:
    host: xxx
    port: 5672
    password: guest
    username: guest
  # Redis 配置
  redis:
    database: 0
    host: xxx
    port: 6379
    timeout: 10000
    password: 123456
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 鱼聪明API
yuapi:
  client:
    access-key: xxx
    secret-key: xxx